### ISSUE TITLE
Recommend docker image for Cloud Build?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [r-hub/rhub#317]
Hello :)

I would like to run a rhub check on a package uploaded to GitHub using Cloud Build.  Is there a recommended Docker image I can use to do that?  The format I am looking to support I think will be something like:

```yaml
steps: 
   - name: rhub/docker-image
      cmd: ["R", "-e", "rhub::check()"]

```
