### ISSUE TITLE
setup job fails when clang-ubsan is included

### ISSUE THREAD

**Issue by ctoney** [r-hub/rhub#656]
Such an awesome service! Thank you for the excellent work here.

I've been using clang-asan and valgrind regularly for some time now and they are tremendously helpful.

If I include the new clang-ubsan alone or in combination with other checks, the action always fails at setup, cf.
https://github.com/ctoney/gdalraster/actions/runs/13575477164
vs
https://github.com/ctoney/gdalraster/actions/runs/13575486550

Or in combination: https://github.com/ctoney/gdalraster/actions/runs/13575462731

I believe at some point in the recent past, `-fsanitize=undefined` was also used in the clang-asan check. Is the addition of clang-ubsan intended to provide those as separate checks now?

**Comment by gaborcsardi** [comment]
You need to use a newer release, you are hard-coding an older one:
https://github.com/ctoney/gdalraster/blob/d32f80b91739a353c0fd6aaf44be64dd12a4f25e/.github/workflows/rhub.yaml#L38
```yaml
    steps:
    # NO NEED TO CHECKOUT HERE
    - uses: r-hub/actions/setup@1607aa150e4d33e2b4a2005c214c27dff7b792e9 # v1.5.0
      with:
        config: ${{ github.event.inputs.config }}
      id: rhub-setup
```
