### ISSUE TITLE
can I specify compact-vignettes=both?

### ISSUE THREAD

**Issue by bbolker** [r-hub/rhub#659]
In a previous version of the rhub workflow I was able to add a `compact-vignettes` specification to the checking run as follows:

```
      - uses: r-hub/rhub2/actions/rhub-run-check@v1
        with:
          job-config: ${{ matrix.config.job-config }}
          token: ${{ secrets.RHUB_TOKEN }}
          build_args: 'c("--compact-vignettes=both")'
```

When I make the same modification with the current action (`r-hub/actions/run-check@v1`), I get a warning ...

> Warning: Unexpected input(s) 'build_args', valid inputs are ['token', 'job-config', 'remove-dot-github']

and then the check fails because I haven't compacted my vignettes sufficiently:

```
❯ checking sizes of PDF files under 'inst/doc' ... WARNING
    'gs+qpdf' made some significant size reductions:
       compacted 'lmer.pdf' from 838Kb to 512Kb
    consider running tools::compactPDF(gs_quality = "ebook") on these files,
    or build the source package with --compact-vignettes=both
```

Keeping in mind that I may have screwed something up and that GHA yaml is more or less black magic for me, do you have any suggestions?  (workflow file [here](https://github.com/lme4/lme4/blob/master/.github/workflows/rhub.yaml): it's standard except for a rule to add a bunch of LaTeX packages)
